#ifndef _PLYODINE_ERROR_CODES_
#define _PLYODINE_ERROR_CODES_

namespace plyodine {

// List of parsing errors that can be returned by plyodine.
enum class ErrorCode : int {
  BAD_STREAM = 1,

  //
  // Header Parsing Errors
  //

  HEADER_MISSING_MAGIC_STRING = 0x100,
  HEADER_CONTAINS_MISMATCHED_LINE_ENDINGS = 0x101,
  HEADER_CONTAINS_INVALID_CHARACTER = 0x102,
  HEADER_LINE_STARTS_WITH_WHITESPACE = 0x103,
  HEADER_LINE_ENDS_WITH_WHITESPACE = 0x104,
  HEADER_LINE_CONTAINS_EXTRA_WHITESPACE = 0x105,
  HEADER_MISSING_FORMAT_SPECIFIER = 0x106,
  HEADER_SPECIFIED_INVALID_FORMAT = 0x107,
  HEADER_SPECIFIED_UNSUPPORTED_VERSION = 0x108,
  HEADER_FORMAT_SPECIFIER_TOO_LONG = 0x109,
  HEADER_NAKED_PROPERTY = 0x10A,
  HEADER_PROPERTY_SPECIFIER_TOO_SHORT = 0x10B,
  HEADER_PROPERTY_SPECIFIED_INVALID_TYPE = 0x10C,
  HEADER_PROPERTY_SPECIFIED_LIST_TYPE_FLOAT = 0x10D,
  HEADER_PROPERTY_SPECIFIED_LIST_TYPE_DOUBLE = 0x10E,
  HEADER_PROPERTY_SPECIFIED_DUPLICATE_NAME = 0x10F,
  HEADER_PROPERTY_SPECIFIER_TOO_LONG = 0x110,
  HEADER_ELEMENT_SPECIFIER_TOO_SHORT = 0x111,
  HEADER_ELEMENT_SPECIFIED_DUPLICATE_NAME = 0x112,
  HEADER_ELEMENT_COUNT_OUT_OF_RANGE = 0x113,
  HEADER_ELEMENT_COUNT_PARSING_FAILED = 0x114,
  HEADER_ELEMENT_SPECIFIER_TOO_LONG = 0x115,
  HEADER_END_INVALID = 0x116,
  HEADER_UNRECOGNIZED_KEYWORD = 0x117,

  //
  // Body Parsing Errors
  //

  READER_UNEXPECTED_EOF = 0x200,
  READER_CONTAINS_MISMATCHED_LINE_ENDINGS = 0x201,
  READER_CONTAINS_INVALID_CHARACTER = 0x202,
  READER_NEGATIVE_LIST_SIZE = 0x203,
  READER_ELEMENT_TOO_FEW_TOKENS = 0x204,
  READER_ELEMENT_CONTAINS_EXTRA_WHITESPACE = 0x205,
  READER_ELEMENT_CONTAINS_EXTRA_TOKENS = 0x206,
  READER_ELEMENT_LIST_SIZE_OUT_OF_RANGE = 0x207,
  READER_ELEMENT_PROPERTY_OUT_OF_RANGE = 0x208,
  READER_ELEMENT_LIST_SIZE_PARSING_FAILED = 0x209,
  READER_ELEMENT_PROPERTY_PARSING_FAILED = 0x20A,

  //
  // Write Errors
  //

  WRITER_WRITE_ERROR = 0x300,
  WRITER_COMMENT_CONTAINS_NEWLINE = 0x301,
  WRITER_OBJ_INFO_CONTAINS_NEWLINE = 0x302,
  WRITER_EMPTY_NAME_SPECIFIED = 0x303,
  WRITER_NAME_CONTAINED_INVALID_CHARACTERS = 0x304,
  WRITER_LIST_INDEX_TOO_SMALL = 0x305,
  WRITER_ASCII_FLOAT_NOT_FINITE = 0x306,
};

}  // namespace plyodine

#endif  // _PLYODINE_ERROR_CODES_