name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        include:
          - runs-on: ubuntu-24.04
            compiler: gcc
            gcc: 14
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: debug build
      run: bazel build --repo_env=CC=g++14 ...

    - name: debug tests
      run: bazel test --repo_env=CC=g++14 ...

    - name: optimized build
      run: bazel build --repo_env=CC=g++14 -c opt ...

    - name: optimized tests
      run: bazel test --repo_env=CC=g++14 -c opt ...